2020-08-06 01:18:22,750 ERROR: Exception on /search [GET] [in /home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/vasco/Desktop/wswebdev/microblog/app/main/routes.py", line 152, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "/home/vasco/Desktop/wswebdev/microblog/app/models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/vasco/Desktop/wswebdev/microblog/app/search.py", line 22, in query_index
    search = current_app.elasticsearch.search(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 139, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1479, in search
    return self.transport.perform_request(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/elasticsearch/transport.py", line 345, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 256, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 287, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2020-08-06 01:29:31,906 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:77]
2020-08-06 01:29:35,818 ERROR: Exception on /search [GET] [in /home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/vasco/Desktop/wswebdev/microblog/app/main/routes.py", line 152, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "/home/vasco/Desktop/wswebdev/microblog/app/models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/vasco/Desktop/wswebdev/microblog/app/search.py", line 22, in query_index
    search = current_app.elasticsearch.search(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 139, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1479, in search
    return self.transport.perform_request(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/elasticsearch/transport.py", line 345, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 256, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 287, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
