2020-06-06 16:16:00,334 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:42]
2020-06-06 16:16:13,257 ERROR: Exception on /edit_profile [POST] [in /home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1283, in _execute_context
    self.dialect.do_execute(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/vasco/Desktop/wswebdev/microblog/app/routes.py", line 87, in edit_profile
    db.session.commit()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2624, in _flush
    flush_context.execute()
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 230, in save_obj
    _emit_update_statements(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 994, in _emit_update_statements
    c = cached_connections[connection].execute(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1323, in _execute_context
    self._handle_dbapi_exception(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1517, in _handle_dbapi_exception
    util.raise_(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1283, in _execute_context
    self.dialect.do_execute(
  File "/home/vasco/Desktop/wswebdev/tutorial-env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('RitaM', 'Ol√° eu gosto da Rita', 1)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2020-06-06 16:21:54,657 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:42]
2020-06-06 17:16:58,911 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:42]
2020-06-06 17:17:12,488 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:42]
2020-06-06 17:57:52,608 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:42]
2020-06-06 18:35:46,366 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:42]
2020-06-13 10:26:23,715 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:42]
2020-06-13 10:38:00,713 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:42]
2020-06-13 10:44:22,222 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:42]
2020-06-13 10:48:18,828 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:42]
2020-06-13 10:50:20,142 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:42]
2020-06-13 12:16:22,834 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:42]
2020-06-13 12:19:40,942 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:42]
2020-06-13 12:23:53,815 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:42]
2020-06-13 12:30:56,427 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:44]
2020-06-13 12:38:14,475 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:44]
2020-06-13 13:30:50,138 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:44]
2020-06-13 15:50:50,835 INFO: Microblog startup [in /home/vasco/Desktop/wswebdev/microblog/app/__init__.py:44]
